"""initial schema

Revision ID: 304305ca0d9f
Revises: 
Create Date: 2026-09-26 15:47:01.558861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304305ca0d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('map_x', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('map_y', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('max_speed_kmh', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_station_id', 'to_station_id', name='uq_section_from_to')
    )
    op.create_table('trains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('train_type', sa.String(length=50), nullable=True),
    sa.Column('origin_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.Time(), nullable=True),
    sa.Column('scheduled_departure', sa.Time(), nullable=True),
    sa.Column('distance_from_origin_km', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('day_offset', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'station_id', name='uq_route_train_station'),
    sa.UniqueConstraint('train_id', 'stop_sequence', name='uq_route_train_sequence')
    )
    op.create_table('section_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('condition_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('delay_impact_min', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_station_id', sa.Integer(), nullable=True),
    sa.Column('next_station_id', sa.Integer(), nullable=True),
    sa.Column('current_speed_kmh', sa.SmallInteger(), nullable=True),
    sa.Column('current_delay_min', sa.SmallInteger(), nullable=False),
    sa.Column('route_progress_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('map_x', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('map_y', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['next_station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'run_date', name='uq_run_train_date')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_run_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_run_id'], ['train_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delay_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_run_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('track_congestion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preceding_train_delay_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('station_dwell_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_restriction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('other_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['train_run_id'], ['train_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eta_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('train_run_id', sa.Integer(), nullable=False),
    sa.Column('target_station_id', sa.Integer(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_lower', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_upper', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uncertainty_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('improvement_min', sa.SmallInteger(), nullable=True),
    sa.Column('model_version', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['target_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_run_id'], ['train_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stop_actuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_run_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_delay_min', sa.SmallInteger(), nullable=True),
    sa.Column('departure_delay_min', sa.SmallInteger(), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_run_id'], ['train_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_run_id', 'station_id', name='uq_stop_actual_run_station')
    )
    op.create_table('train_movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('train_run_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('speed_kmh', sa.SmallInteger(), nullable=True),
    sa.Column('delay_min', sa.SmallInteger(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['train_run_id'], ['train_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_movements')
    op.drop_table('stop_actuals')
    op.drop_table('eta_predictions')
    op.drop_table('delay_factors')
    op.drop_table('alerts')
    op.drop_table('train_runs')
    op.drop_table('section_conditions')
    op.drop_table('routes')
    op.drop_table('trains')
    op.drop_table('sections')
    op.drop_table('stations')
    op.drop_table('zones')
    # ### end Alembic commands ###
