import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, BrainCircuit, ChevronDown, CircleUserRound, Moon, Pause, Play, RotateCcw, Search, Sparkles, Sun, TrainFront, Zap } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Toaster } from "@/components/ui/sonner";
import { KpiCard, Metric, Panel, StatusDot } from "./Primitives";
import { TrainMap } from "./TrainMap";
import { chartData, delayFactors, initialAlerts, stations, trains as sourceTrains, zones, type Train } from "@/data/demo";

const nav = ["Dashboard", "Live Trains", "ETA Prediction", "Network Monitor", "Delay Analytics", "Model Performance", "Alerts", "API / Integration"];

export default function Dashboard() {
  const [view, setView] = useState("Dashboard");
  const [selected, setSelected] = useState(sourceTrains[0]);
  const [running, setRunning] = useState(true);
  const [simMode, setSimMode] = useState(true);
  const [speed, setSpeed] = useState(1);
  const [tick, setTick] = useState(0);
  const [congestion, setCongestion] = useState(false);
  const [dark, setDark] = useState(false);
  const [query, setQuery] = useState("");
  const [alerts, setAlerts] = useState(initialAlerts);

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
  }, [dark]);
  useEffect(() => {
    if (!running || !simMode) return;
    const id = window.setInterval(() => setTick((v) => v + 1), 3000 / speed);
    return () => window.clearInterval(id);
  }, [running, simMode, speed]);

  const liveSelected = useMemo(() => ({ ...selected, speed: Math.max(48, selected.speed + ((tick % 5) - 2)), confidence: Math.max(78, selected.confidence - (congestion ? 6 : 0) + (tick % 2)), delay: selected.delay + (congestion ? 8 : 0), aiEta: congestion && selected.number === "12951" ? "21:39" : selected.aiEta, range: congestion && selected.number === "12951" ? "21:34 – 21:44" : selected.range }), [selected, tick, congestion]);
  const filtered = sourceTrains.filter((t) => `${t.number} ${t.name} ${t.current}`.toLowerCase().includes(query.toLowerCase()));

  function triggerCongestion() {
    if (congestion) return;
    setCongestion(true);
    setAlerts((a) => [{ severity: "critical", time: "NOW", title: "Vadodara → Ratlam", reason: "Simulated congestion event triggered", impact: "+8 min", action: "Recalculate precedence plan" }, ...a]);
    toast.error("Critical congestion detected", { description: "Train 12951 AI ETA revised to 21:39." });
  }

  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <Toaster position="top-right" theme={dark ? "dark" : "light"} />
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md">
      <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-3 py-2.5 lg:px-5">
        <button className="flex min-w-0 items-center gap-3" onClick={() => setView("Dashboard")}><span className="flex size-9 shrink-0 items-center justify-center bg-primary text-primary-foreground"><TrainFront className="size-5" /></span><span className="min-w-0 text-left"><b className="block truncate text-sm tracking-wide">RailPredict <span className="text-primary">AI</span></b><small className="hidden truncate text-[9px] uppercase tracking-[.16em] text-muted-foreground sm:block">Railway Intelligence System</small></span></button>
        <div className="flex shrink-0 items-center gap-1 sm:gap-2"><span className="hidden items-center gap-1.5 text-[10px] font-bold text-success md:flex"><i className="size-2 animate-pulse rounded-full bg-success" /> LIVE</span><span className="hidden font-mono text-[9px] text-muted-foreground lg:block">UPDATED 11:{14 + (tick % 40)}:{String((tick * 3) % 60).padStart(2, "0")} IST</span><Button variant="ghost" size="icon" onClick={() => setDark((v) => !v)} title="Toggle theme">{dark ? <Sun /> : <Moon />}</Button><Button variant="ghost" size="icon" title="Notifications" className="relative"><Bell /><i className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-destructive" /></Button><CircleUserRound className="hidden size-6 text-muted-foreground sm:block" /></div>
      </div>
      <nav className="flex items-center gap-1 overflow-x-auto border-t border-border px-2 lg:px-4 [-webkit-overflow-scrolling:touch]">{nav.map((item) => <button key={item} onClick={() => setView(item)} className={`h-11 shrink-0 whitespace-nowrap border-b-2 px-2.5 text-[11px] font-semibold transition-colors ${view === item ? "border-primary text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{item}</button>)}</nav>
    </header>
    <div className="flex">
      <main className="w-0 min-w-0 flex-1 p-3 lg:p-4">
        <div className="mx-auto max-w-[1700px]">
          <div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div className="min-w-0"><h1 className="text-lg font-semibold tracking-normal sm:text-2xl">{view === "Dashboard" ? "Dynamic ETA Intelligence & Railway Operations Dashboard" : view}</h1></div><SimulationControls running={running} setRunning={setRunning} simMode={simMode} setSimMode={setSimMode} speed={speed} setSpeed={setSpeed} onReset={() => { setTick(0); setCongestion(false); toast.success("Simulation reset"); }} /></div>
          {view === "Dashboard" && <DashboardView selected={liveSelected} setSelected={setSelected} tick={tick} congestion={congestion} triggerCongestion={triggerCongestion} query={query} setQuery={setQuery} filtered={filtered} />}
          {view === "Live Trains" && <LiveTrainsView query={query} setQuery={setQuery} filtered={filtered} onSelect={(t) => { setSelected(t); setView("Dashboard"); }} />}
          {view === "ETA Prediction" && <PredictionView selected={liveSelected} congestion={congestion} triggerCongestion={triggerCongestion} />}
          {view === "Delay Analytics" && <AnalyticsView />}
          {view === "Network Monitor" && <NetworkView congestion={congestion} />}
          {view === "Model Performance" && <ModelView />}
          {view === "Alerts" && <AlertsView alerts={alerts} />}
          {view === "API / Integration" && <ArchitectureView />}
          <div className="mt-4 grid gap-4 xl:grid-cols-2"><PassengerView selected={liveSelected} /><StationDisplay /></div>
          <footer className="mt-6 flex flex-col justify-between gap-2 border-t border-border py-5 text-[10px] uppercase tracking-wider text-muted-foreground sm:flex-row"><span>RailPredict AI · Smart India Hackathon 2026</span><span>Prototype using simulated operational data · Not affiliated with live railway systems</span></footer>
        </div>
      </main>
    </div>
  </div>;
}

function ActivityIcon({ className }: { className?: string }) { return <BarChartIcon className={className ?? ""} />; }
function BarChartIcon({ className = "" }: { className?: string }) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className={className}><path d="M3 3v18h18M7 16v2m4-7v7m4-11v11m4-5v5" /></svg>; }

function SimulationControls({ running, setRunning, simMode, setSimMode, speed, setSpeed, onReset }: { running: boolean; setRunning: (v: boolean) => void; simMode: boolean; setSimMode: (v: boolean) => void; speed: number; setSpeed: (v: number) => void; onReset: () => void }) {
  return <div className="flex flex-wrap items-center gap-1.5 border border-border bg-card p-1.5"><label className="flex items-center gap-2 px-2 text-[10px] font-semibold uppercase tracking-wider"><Switch checked={simMode} onCheckedChange={setSimMode} /> Simulation</label><Button size="sm" variant={running ? "secondary" : "default"} onClick={() => setRunning(!running)}>{running ? <Pause /> : <Play />}{running ? "Pause" : "Start"}</Button><Button size="icon" variant="ghost" onClick={onReset} title="Reset simulation"><RotateCcw /></Button>{[1, 2, 5].map((v) => <Button key={v} size="sm" variant={speed === v ? "default" : "ghost"} onClick={() => setSpeed(v)}>{v}x</Button>)}</div>;
}

function DashboardView({ selected, setSelected, tick, congestion, triggerCongestion, query, setQuery, filtered }: { selected: Train; setSelected: (t: Train) => void; tick: number; congestion: boolean; triggerCongestion: () => void; query: string; setQuery: (v: string) => void; filtered: Train[] }) {
  const spark = (n: number) => Array.from({ length: 8 }, (_, i) => n + Math.sin(i + tick) * n * .05);
  return <>
    <div className="mb-4 grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6"><KpiCard label="Live trains" value="1,248" change="2.4%" data={spark(60)} /><KpiCard label="On-time trains" value="78.6%" change="1.8%" tone="success" data={spark(78)} /><KpiCard label="Delayed trains" value={congestion ? "222" : "214"} change={congestion ? "+3.7%" : "-4.2%"} tone="danger" data={spark(45)} /><KpiCard label="Avg network delay" value={congestion ? "19 min" : "18 min"} change="+1.2%" tone="warning" data={spark(20)} /><KpiCard label="ETA accuracy" value="91.8%" change="2.1%" tone="success" data={spark(88)} /><KpiCard label="Active alerts" value={congestion ? "18" : "17"} change={congestion ? "+5.9%" : "-8.4%"} tone="danger" data={spark(17)} /></div>
    <div className="mb-4 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(330px,.75fr)]"><Panel title="Live Railway Network" kicker="Western–Northern corridor" action={<span className="flex items-center gap-1.5 text-[10px] text-live"><i className="size-1.5 animate-pulse rounded-full bg-live" /> POSITION STREAM ACTIVE</span>}><TrainMap trains={sourceTrains.map((t, i) => ({ ...t, y: t.y + ((tick + i) % 4) * .25 }))} selected={selected} onSelect={setSelected} congestion={congestion} /></Panel><TrainDetail train={selected} congestion={congestion} triggerCongestion={triggerCongestion} /></div>
    <CapabilityStrip />
    <div className="my-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><PredictionPanel selected={selected} congestion={congestion} /><FactorsPanel congestion={congestion} /></div>
    <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><StationTable /><Panel title="Train Search" kicker="Live operational feed"><SearchBox query={query} setQuery={setQuery} /> <div className="divide-y divide-border">{filtered.slice(0, 4).map((t) => <button onClick={() => setSelected(t)} key={t.number} className="grid w-full grid-cols-[1fr_auto] items-center gap-3 p-3 text-left transition-colors hover:bg-accent"><div><p className="text-xs font-semibold">{t.number} · {t.shortName}</p><p className="mt-1 text-[10px] text-muted-foreground">{t.current} → {t.destination}</p></div><div className="text-right"><p className="font-mono text-xs text-live">AI {t.aiEta}</p><p className="mt-1 text-[9px] text-muted-foreground">{t.confidence}% CONF.</p></div></button>)}</div></Panel></div>
  </>;
}

function TrainDetail({ train, congestion, triggerCongestion }: { train: Train; congestion: boolean; triggerCongestion: () => void }) {
  return <Panel title={`${train.number} · ${train.shortName}`} kicker="Selected train" action={<StatusDot status={train.status} />} className="h-full"><div className="p-4"><div className="mb-4 flex items-center gap-3 border-b border-border pb-4"><div className="flex size-10 items-center justify-center bg-primary/10 text-primary"><TrainFront /></div><div><p className="text-sm font-semibold">{train.current}</p><p className="text-[10px] text-muted-foreground">Next · {train.next}</p></div><div className="ml-auto text-right"><p className="font-mono text-lg font-semibold">{train.speed} <span className="text-[10px] text-muted-foreground">km/h</span></p><p className="text-[9px] uppercase text-live">Movement verified</p></div></div><div className="grid grid-cols-2 gap-x-4 gap-y-4"><Metric label="Current delay" value={`+${train.delay} min`} /><Metric label="Distance remaining" value="684 km" /><Metric label="Scheduled ETA" value={train.scheduled} /><Metric label="Current ETA" value={train.currentEta} /><Metric label="AI Predicted ETA" value={train.aiEta} accent /><Metric label="Prediction improvement" value={congestion ? "-3 min" : "-11 min"} /></div><div className="mt-5"><div className="mb-2 flex justify-between text-[10px]"><span className="uppercase text-muted-foreground">Route progress</span><span className="font-mono">{train.progress}%</span></div><div className="h-1.5 bg-muted"><div className="h-full bg-live transition-all" style={{ width: `${train.progress}%` }} /></div></div><div className="mt-5 border-l-2 border-live bg-live/5 p-3"><div className="flex justify-between"><span className="text-[10px] uppercase text-muted-foreground">Prediction confidence</span><b className="font-mono text-live">{train.confidence}%</b></div><p className="mt-1 font-mono text-sm">Range · {train.range}</p></div><Button onClick={triggerCongestion} disabled={congestion} variant={congestion ? "secondary" : "destructive"} className="mt-4 w-full"><AlertTriangle />{congestion ? "Congestion Event Active" : "Trigger Congestion Event"}</Button></div></Panel>;
}

function CapabilityStrip() { return <div className="grid border border-border bg-card md:grid-cols-3">{[[BrainCircuit, "Predict", "Continuously recalculates arrival time"], [Sparkles, "Explain", "Attributes operational impact by factor"], [Zap, "Respond", "Revises ETAs and creates actionable alerts"]].map(([I, a, b], i) => { const Icon = I as typeof BrainCircuit; return <div key={String(a)} className={`flex items-center gap-3 p-4 ${i < 2 ? "border-b border-border md:border-b-0 md:border-r" : ""}`}><span className="flex size-9 items-center justify-center bg-primary/10 text-primary"><Icon className="size-4" /></span><div><p className="text-xs font-bold uppercase tracking-[.14em]">{String(a)}</p><p className="mt-1 text-[10px] text-muted-foreground">{String(b)}</p></div></div>; })}</div>; }

function PredictionPanel({ selected, congestion }: { selected: Train; congestion: boolean }) {
  return <Panel title="AI ETA Prediction" kicker="Dynamic comparison" action={<span className="font-mono text-xs text-live">CONF {selected.confidence}%</span>}><div className="grid border-b border-border sm:grid-cols-3"><div className="p-4"><Metric label="Scheduled ETA" value="18:40" /></div><div className="border-y border-border p-4 sm:border-x sm:border-y-0"><Metric label="Current Railway ETA" value="18:56" /></div><div className="bg-live/5 p-4"><Metric label="AI Predicted ETA" value={congestion ? "18:55" : "18:49"} accent /><p className="mt-1 text-[10px] text-success">{congestion ? "-1 min" : "-7 min"} vs current</p></div></div><div className="p-4"><div className="mb-4 flex items-center gap-2"><span className="h-1.5 flex-1 bg-muted"><i className="block h-full w-[35%] bg-muted-foreground" /></span><span className="size-2 rounded-full bg-muted-foreground" /><span className="h-1.5 flex-1 bg-orange"><i className="block h-full bg-live transition-all" style={{ width: congestion ? "90%" : "55%" }} /></span><span className="size-3 rounded-full bg-live ring-4 ring-live/15" /></div><div className="flex justify-between text-[9px] uppercase text-muted-foreground"><span>Scheduled 18:40</span><span>Current 18:56</span><span className="text-live">AI {congestion ? "18:55" : "18:49"}</span></div><p className="mt-5 border-l-2 border-primary pl-3 text-xs leading-relaxed text-muted-foreground">AI prediction dynamically updates using real-time train movement, historical sectional delays, congestion and operational conditions.</p></div></Panel>;
}

function FactorsPanel({ congestion }: { congestion: boolean }) { return <Panel title="Operational Factors" kicker="Model-derived · Demo"><div className="space-y-4 p-4">{delayFactors.map(([label, value], i) => { const adjusted = congestion && i === 0 ? 49 : value; return <div key={label}><div className="mb-1.5 flex justify-between text-[10px]"><span>{label}</span><b className="font-mono">{adjusted}%</b></div><div className="h-1.5 bg-muted"><div className={`h-full transition-all duration-700 ${i === 0 ? "bg-destructive" : i < 3 ? "bg-orange" : "bg-live"}`} style={{ width: `${adjusted}%` }} /></div></div>; })}</div></Panel>; }

function StationTable() { return <Panel title="Upcoming Stations" kicker="Train 12951"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-muted/60 text-[9px] uppercase tracking-wider text-muted-foreground"><tr>{["Station", "Scheduled ETA", "Current ETA", "AI ETA", "Delay", "Confidence"].map((h) => <th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{stations.map((s) => <tr key={s.station} className="hover:bg-accent"><td className="px-4 py-3 font-semibold">{s.station}</td><td className="px-4 py-3 font-mono text-muted-foreground">{s.scheduled}</td><td className="px-4 py-3 font-mono">{s.current}</td><td className="px-4 py-3 font-mono font-semibold text-live">{s.ai}</td><td className="px-4 py-3"><span className="bg-warning/10 px-1.5 py-1 font-mono text-warning">+{s.delay} min</span></td><td className="px-4 py-3 font-mono">{s.confidence}%</td></tr>)}</tbody></table></div></Panel>; }

function SearchBox({ query, setQuery }: { query: string; setQuery: (v: string) => void }) { return <div className="border-b border-border p-3"><div className="flex items-center gap-2 border border-input bg-background px-3"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground" placeholder="Search train number, train name or station..." /><Button size="icon" variant="ghost" title="Filters"><ChevronDown /></Button></div></div>; }

function LiveTrainsView({ query, setQuery, filtered, onSelect }: { query: string; setQuery: (v: string) => void; filtered: Train[]; onSelect: (t: Train) => void }) { return <Panel title="Live Train Search" kicker="1,248 active movements"><SearchBox query={query} setQuery={setQuery} /><div className="flex flex-wrap gap-2 border-b border-border p-3">{["Zone", "Train Type", "Delay Status", "Route", "Date", "Prediction Confidence"].map((f) => <Button key={f} variant="outline" size="sm">{f}<ChevronDown /></Button>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-muted/60 text-[9px] uppercase tracking-wider text-muted-foreground"><tr>{["Train", "Current location", "Destination", "Current delay", "Scheduled ETA", "AI ETA", "Confidence", "Status"].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((t) => <tr key={t.number} onClick={() => onSelect(t)} className="cursor-pointer hover:bg-accent"><td className="px-4 py-4"><b>{t.number}</b><p className="mt-1 text-[10px] text-muted-foreground">{t.shortName}</p></td><td className="px-4">{t.current}</td><td className="px-4">{t.destination}</td><td className="px-4 font-mono text-warning">+{t.delay} min</td><td className="px-4 font-mono">{t.scheduled}</td><td className="px-4 font-mono font-bold text-live">{t.aiEta}</td><td className="px-4 font-mono">{t.confidence}%</td><td className="px-4"><span className="flex items-center gap-2 capitalize"><StatusDot status={t.status} />{t.status}</span></td></tr>)}</tbody></table></div></Panel>; }

function PredictionView({ selected, congestion, triggerCongestion }: { selected: Train; congestion: boolean; triggerCongestion: () => void }) { return <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><PredictionPanel selected={selected} congestion={congestion} /><TrainDetail train={selected} congestion={congestion} triggerCongestion={triggerCongestion} /></div><Panel title="ETA Prediction Curve" kicker="Scheduled vs current vs AI"><div className="h-[340px] p-4"><ResponsiveContainer><LineChart data={chartData}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="station" stroke="var(--muted-foreground)" fontSize={10} /><YAxis stroke="var(--muted-foreground)" fontSize={10} domain={[18, 34]} /><ChartTooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 0 }} /><Legend /><Line dataKey="scheduled" name="Scheduled ETA" stroke="var(--muted-foreground)" strokeDasharray="5 4" /><Line dataKey="current" name="Current ETA" stroke="var(--orange)" strokeWidth={2} /><Line dataKey="ai" name="AI Predicted ETA" stroke="var(--live)" strokeWidth={3} /></LineChart></ResponsiveContainer></div></Panel><StationTable /></div>; }

function AnalyticsView() { const dist = [{ n: "0–10", v: 48 }, { n: "10–30", v: 31 }, { n: "30–60", v: 15 }, { n: "60+", v: 6 }]; return <div className="grid gap-4 lg:grid-cols-2"><ChartPanel title="Delay Distribution" data={dist} dataKey="v" /><ChartPanel title="Delay by Railway Zone" data={zones} dataKey="delay" /><Panel title="Historical vs Predicted Delay" kicker="Rolling 8-hour window" className="lg:col-span-2"><div className="h-72 p-4"><ResponsiveContainer><AreaChart data={chartData}><CartesianGrid stroke="var(--border)" /><XAxis dataKey="station" stroke="var(--muted-foreground)" fontSize={10} /><YAxis stroke="var(--muted-foreground)" fontSize={10} /><ChartTooltip /><Area dataKey="current" stroke="var(--orange)" fill="var(--orange-soft)" /><Area dataKey="ai" stroke="var(--live)" fill="var(--live-soft)" /></AreaChart></ResponsiveContainer></div></Panel><FactorsPanel congestion={false} /><Panel title="Top Delay-Causing Sections" kicker="Operational ranking"><div className="divide-y divide-border">{[["Vadodara → Ratlam", "17", "22", "19"], ["Kota → Mathura", "14", "18", "16"], ["Surat → Bharuch", "11", "14", "12"]].map((r) => <div key={r[0]} className="grid grid-cols-[1fr_repeat(3,auto)] gap-5 p-4 text-xs"><b>{r[0]}</b><span className="font-mono text-muted-foreground">H {r[1]}m</span><span className="font-mono text-orange">C {r[2]}m</span><span className="font-mono text-live">AI {r[3]}m</span></div>)}</div></Panel></div>; }

function ChartPanel({ title, data, dataKey }: { title: string; data: Array<{ n?: string; name?: string; [key: string]: string | number | undefined }>; dataKey: string }) { const axisKey = data[0]?.n ? "n" : "name"; return <Panel title={title} kicker="Simulated network data"><div className="h-64 p-4"><ResponsiveContainer><BarChart data={data}><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey={axisKey} stroke="var(--muted-foreground)" fontSize={10} /><YAxis stroke="var(--muted-foreground)" fontSize={10} /><ChartTooltip contentStyle={{ background: "var(--card)", border: "1px solid var(--border)" }} /><Bar dataKey={dataKey} fill="var(--live)" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></div></Panel>; }

function NetworkView({ congestion }: { congestion: boolean }) { return <><div className="mb-4 grid grid-cols-2 gap-2 lg:grid-cols-5"><KpiCard label="Network status" value="Operational" change="Stable" tone="success" data={[5,5,5,5]} /><KpiCard label="Active sections" value="1,842" change="1.1%" data={[20,22,23,24]} /><KpiCard label="Congested sections" value={congestion ? "127" : "126"} change="+3.2%" tone="warning" data={[10,12,11,14]} /><KpiCard label="Critical sections" value={congestion ? "19" : "18"} change="+5.6%" tone="danger" data={[3,4,3,5]} /><KpiCard label="Avg section delay" value="14.7m" change="-2.1%" tone="success" data={[18,17,16,14]} /></div><Panel title="Network Congestion Heatmap" kicker="All India sectional overview"><div className="grid min-h-[460px] place-items-center bg-map-grid p-6"><div className="grid w-full max-w-4xl grid-cols-6 gap-2">{Array.from({ length: 48 }, (_, i) => <div key={i} className={`h-10 border border-border ${i % 13 === 0 ? "bg-destructive/70" : i % 7 === 0 ? "bg-orange/60" : i % 4 === 0 ? "bg-warning/40" : "bg-success/20"}`} title={`Section ${i + 1}`} />)}</div></div></Panel></>; }

function ModelView() { const data = zones.map((z) => ({ ...z, target: 95 })); return <><div className="mb-4 grid grid-cols-2 gap-2 lg:grid-cols-5"><KpiCard label="MAE" value="6.8 min" change="-0.4" tone="success" data={[8,7.7,7.3,6.8]} /><KpiCard label="RMSE" value="9.4 min" change="-0.7" tone="success" data={[11,10.5,10,9.4]} /><KpiCard label="Prediction accuracy" value="91.8%" change="2.1%" data={[88,89,90,92]} /><KpiCard label="Within ±5 min" value="72.4%" change="1.7%" data={[68,70,71,72]} /><KpiCard label="Within ±10 min" value="89.2%" change="2.4%" data={[84,86,88,89]} /></div><div className="grid gap-4 lg:grid-cols-2"><ChartPanel title="Accuracy by Railway Zone" data={data} dataKey="accuracy" /><Panel title="Actual vs Predicted ETA" kicker="Demo model evaluation"><div className="h-64 p-4"><ResponsiveContainer><LineChart data={chartData}><CartesianGrid stroke="var(--border)" /><XAxis dataKey="station" stroke="var(--muted-foreground)" fontSize={10} /><YAxis stroke="var(--muted-foreground)" fontSize={10} /><ChartTooltip /><Line dataKey="current" name="Actual" stroke="var(--orange)" /><Line dataKey="ai" name="Predicted" stroke="var(--live)" strokeWidth={2} /></LineChart></ResponsiveContainer></div></Panel></div><p className="mt-3 text-[10px] uppercase tracking-wider text-muted-foreground">All metrics are simulated model evaluation results for demonstration purposes.</p></>; }

function AlertsView({ alerts }: { alerts: typeof initialAlerts }) { return <Panel title="Real-Time Alert Center" kicker={`${alerts.length} active operational alerts`}><div className="divide-y divide-border">{alerts.map((a, i) => <div key={`${a.time}-${i}`} className="grid gap-4 p-4 sm:grid-cols-[80px_1fr_auto]"><div><StatusDot status={a.severity} /><p className="mt-2 font-mono text-[10px] text-muted-foreground">{a.time}</p></div><div><p className="text-xs font-semibold">{a.title}</p><p className="mt-1 text-xs text-muted-foreground">{a.reason}</p><p className="mt-2 text-[10px] uppercase text-live">Recommended · {a.action}</p></div><div className="font-mono text-sm text-warning">{a.impact}</div></div>)}</div></Panel>; }

function ArchitectureView() { const steps = ["Live Train Location", "Operational Data", "Historical Delay Data", "Network + Weather", "Data Processing", "Feature Engineering", "ML / Statistical Model", "Dynamic ETA Prediction", "Passenger · Station · Control Room"]; return <div className="grid gap-4 xl:grid-cols-[1fr_.75fr]"><Panel title="How RailPredict AI Works" kicker="Continuous prediction pipeline"><div className="p-5">{steps.map((s, i) => <div key={s} className="flex flex-col items-center"><div className={`w-full border p-3 text-center text-xs font-semibold uppercase tracking-wider ${i === 7 ? "border-live bg-live/10 text-live" : "border-border bg-elevated"}`}>{s}</div>{i < steps.length - 1 && <div className="h-5 w-px animate-pulse bg-primary" />}</div>)}</div></Panel><Panel title="Technology Architecture" kicker="API-ready modular platform"><div className="space-y-3 p-5">{[["Frontend", "React · Tailwind CSS · Recharts"], ["API Layer", "REST API · FastAPI / Node.js"], ["Data Processing", "Python · Pandas · NumPy"], ["Prediction Model", "Scikit-learn · XGBoost"], ["Persistence", "PostgreSQL"], ["Maps", "Leaflet / Mapbox-ready adapter"]].map(([a,b]) => <div key={a} className="border-l-2 border-primary bg-elevated p-3"><p className="text-[9px] uppercase tracking-wider text-muted-foreground">{a}</p><p className="mt-1 text-xs font-semibold">{b}</p></div>)}<div className="mt-5 border border-live/30 bg-live/5 p-4"><p className="text-xs font-semibold text-live">Integration-ready data contracts</p><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">Simulated sources are isolated from presentation, enabling future replacement with authenticated railway operational APIs.</p></div></div></Panel></div>; }

function PassengerView({ selected }: { selected: Train }) { return <Panel title="Passenger View" kicker="Simplified prediction experience"><div className="p-5"><div className="mb-4 flex items-start justify-between"><div><p className="font-mono text-2xl font-bold">{selected.number}</p><p className="text-xs text-muted-foreground">{selected.shortName}</p></div><span className="flex items-center gap-1.5 bg-success/10 px-2 py-1 text-[10px] font-semibold text-success"><StatusDot status="on-time" /> On Route</span></div><div className="grid grid-cols-2 gap-4 border-y border-border py-4"><Metric label="Current location" value={selected.current} /><Metric label="Next station" value={selected.next} /><Metric label="Expected arrival" value={selected.aiEta} accent /><Metric label="Scheduled" value={selected.scheduled} /></div><p className="mt-4 text-xs text-muted-foreground"><b className="text-success">AI prediction:</b> 11 min earlier than the current schedule-adjusted estimate.</p></div></Panel>; }

function StationDisplay() { const rows = [["12951", "Mumbai Rajdhani", "New Delhi", "4", "21:42", "21:31", "EXPECTED"], ["12932", "Double Decker", "Mumbai Central", "2", "21:55", "22:04", "DELAYED"], ["12009", "Shatabdi Express", "Ahmedabad", "1", "22:10", "22:08", "ON TIME"]]; return <Panel title="Station Display Simulation" kicker="Vadodara Junction"><div className="bg-display p-4 font-mono"><div className="mb-3 grid grid-cols-[1.3fr_.7fr_.4fr_.5fr] gap-2 text-[9px] uppercase text-display-muted"><span>Train / Destination</span><span>Expected</span><span>PF</span><span>Status</span></div>{rows.map((r) => <div key={r[0]} className="grid grid-cols-[1.3fr_.7fr_.4fr_.5fr] items-center gap-2 border-t border-display-line py-3 text-[10px] text-display"><span><b>{r[0]} {r[1]}</b><small className="block text-display-muted">TO {r[2]}</small></span><span className="text-sm">{r[5]}</span><span className="text-sm">{r[3]}</span><span className={r[6] === "DELAYED" ? "text-destructive" : "text-success"}>{r[6]}</span></div>)}</div></Panel>; }